files:
  - source: /lang/en/*.php
    translation: /lang/%two_letters_code%/%original_file_name%
  - source: /resources/ts/config/i18n/en.json
    translation: /resources/ts/config/i18n/%two_letters_code%.json
